install(TARGETS DreamConverter ACNH Core_Util Core_SaveFile Core_SaveStructs)

set(CPACK_GENERATOR "TGZ")

set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")

include(CPack)
